name: Deploy to Massdriver
on:
  push:
    branches: [main]

jobs:
  push_and_deploy:
    runs-on: ubuntu-latest
    env:
      MASSDRIVER_ORG_ID: ${{ secrets.MASSDRIVER_ORG_ID }}
      MASSDRIVER_API_KEY: ${{ secrets.MASSDRIVER_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Massdriver CLI
        uses: massdriver-cloud/actions@v4
      - name: Push Image
        uses: massdriver-cloud/actions/image_push@v4
        with:
          namespace: mclacore
          image-name: rps
          artifact: ${{ secrets.AUTHENTICATION_ARTIFACT_ID }}
          region: westus
          image-tag: ${{ github.sha }}
      - name: Publish Bundle 
        uses: massdriver-cloud/actions/bundle_publish@v4
        with:
          build-directory: ./massdriver
      - name: Set App1 Image Version
        uses: massdriver-cloud/actions/app_patch@v4
        with:
          project: script
          env: eastus
          manifest: rps
          set: |
            .image.tag = "${{ github.sha }}"
      - name: Set App2 Image Version
        uses: massdriver-cloud/actions/app_patch@v4
        with:
          project: script
          env: westus
          manifest: rps
          set: |
            .image.tag = "${{ github.sha }}"
      - name: Deploy App1
        uses: massdriver-cloud/actions/app_deploy@v4
        with:
          project: script
          env: eastus
          manifest: rps
      - name: Deploy App2
        uses: massdriver-cloud/actions/app_deploy@v4
        with:
          project: script
          env: westus
          manifest: rps
